# Generated by Django 5.1.3 on 2025-01-23 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modernmarket', '0002_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='modernmarket.store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
