# Generated by Django 5.1.3 on 2025-01-23 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modernmarket', '0003_product_product_key_alter_store_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sold_date',
            new_name='created_at',
        ),
    ]
