# Generated by Django 5.1.3 on 2025-01-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modernmarket', '0004_rename_sold_date_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='password',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
